### ISSUE TITLE
inventory-upload.py cause host hang.

### ISSUE THREAD

**Issue by Kenthliu** [openbmc/openpower-inventory-upload#3]
We found the demi decode will cause host hang in different stage. After I kill inventory-upload process, the symptom gone. We saw ECC error, vpd error, and kexec load failed in petiboot.
[vpderror.txt](https://github.com/openbmc/openpower-inventory-upload/files/290873/vpderror.txt)
[ECCerror.txt](https://github.com/openbmc/openpower-inventory-upload/files/290874/ECCerror.txt)
![img_1973](https://cloud.githubusercontent.com/assets/15260220/15671817/79e6e37a-275f-11e6-8463-78dd3ac30ac1.JPG)
Attach the journalctl log.
[journal.txt](https://github.com/openbmc/openpower-inventory-upload/files/290876/journal.txt)

**Comment by sannerd** [comment]
A couple of thoughts -- the VPD error and ECC error are likely due to the BMC trying to write the PNOR and the Host reading it at the same time (I saw something similar when openBMC was mucking with the PNOR during a watchdog). 

 I don't know what the inventory-upload on the BMC is doing... but if you manually write data do you still see issues?

**Comment by Kenthliu** [comment]
Yes, I have the same idea. Theoretically, BMC can not impact to host, when I saw kexec load failed, it always the same next boot. So I suspect pnor crash by BMC.

**Comment by sannerd** [comment]
I asked Brad to take a look

**Comment by Kenthliu** [comment]
Hi @bradbishop If there is any update or need help, please let me know. Thanks.

**Comment by anoo1** [comment]
This is being fixed with PRs:
https://github.com/openbmc/openpower-inventory-upload/pull/4
https://github.com/openbmc/phosphor-objmgr/pull/12
https://github.com/openbmc/skeleton/pull/98

**Comment by williamspatrick** [comment]
Closing per @anoo1 .
